name: tesla
description: "Tesla project"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 国际化支持
  flutter_localizations:
    sdk: flutter

  # Cupertino 图标
  cupertino_icons: ^1.0.5
  # 高性能的状态管理、智能的依赖注入和便捷的路由管理
  get: ^4.6.5
  # loading / toast
  flutter_easyloading: ^3.0.5
  # 屏幕适配
  flutter_screenutil: ^5.9.0
  # 提供了一个跨平台(iOS，Android)的 API 来请求和检查权限
  permission_handler: ^11.2.0
  # 一个用于 Flutter 的 SVG 渲染和小部件库，它允许绘制和显示可缩放向量图形1.1文件
  flutter_svg: ^2.0.9
  #一个完整的，随时可以使用的，新形象的界面工具包扑动。黑暗的主题兼容和完全可定制。
  neumorphic_ui: ^1.0.1
  # scaffold渐变背景
  scaffold_gradient_background: ^1.0.3+1
  #设置间隔
  gap: ^3.0.1
  # 玻璃效果widget
  glassmorphism: ^3.0.0
  # 简单快速的国际化和本地化你的 Flutter 应用程序，这个软件包简化了国际化过程
  easy_localization: ^3.0.3
  # 网络状态（WiFi和移动/蜂窝）
#  connectivity_plus: ^5.0.2
  #底部导航栏
#  animated_bottom_navigation_bar: ^1.3.2
  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  sleek_circular_slider: ^2.0.1
  provider: ^6.1.2
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/
    - assets/translations/
    - assets/background/
    - assets/lotties/
    - assets/splash_screen/
    - assets/gif/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFProDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Heavy.ttf

flutter_intl:
  enabled: true

# 动态生成app图标
flutter_icons:
  image_path: "assets/launcher_icon/icon1024.png"
  android: true
  ios: true